# Introduction to Pandas
### Data Science and Machine Learning for Engineering Applications

---

**Pandas** is a powerful Python library for data manipulation and analysis. It is built on top of NumPy and provides two key data structures:

- **Series** - a 1-dimensional labeled array
- **DataFrame** - a 2-dimensional labeled table

Pandas makes it easy to:
- Load and save data (CSV, Excel, JSON, …)
- Select, filter and reshape data
- Handle missing values
- Compute statistics and aggregations
- Group and pivot data

Let's start by importing the libraries we will need throughout this notebook.

In [3]:
import pandas as pd
import numpy as np

print('pandas version:', pd.__version__)
print('numpy  version:', np.__version__)

pandas version: 3.0.1
numpy  version: 2.4.2

---
## 1. Pandas Series

A **Series** is a one-dimensional sequence of values, each associated with an **index** label.  
Think of it as a Python list plus a custom index.

```
index:   1       2       3
values:  0.3     0.5     0.8

index:  '3-July' '4-July' '5-July'
values:  0.3      0.5      0.8
```

### 1.1 Creating a Series

In [4]:
# From a list — index is set automatically (0, 1, 2, ...)
s1 = pd.Series([2.0, 3.1, 4.5])
print(s1)

0    2.0
1    3.1
2    4.5
dtype: float64

In [5]:
# From a list with an explicit index
s2 = pd.Series([2.0, 3.1, 4.5], index=['mon', 'tue', 'wed'])
print(s2)

mon    2.0
tue    3.1
wed    4.5
dtype: float64

In [6]:
# From a dictionary — keys become the index
s3 = pd.Series({'c': 2.0, 'b': 3.1, 'a': 4.5})
print(s3)

c    2.0
b    3.1
a    4.5
dtype: float64

### 1.2 Accessing values and index

Every Series exposes `.values` (a NumPy array) and `.index`.

In [7]:
s = pd.Series([2.0, 3.1, 4.5], index=['mon', 'tue', 'wed'])
print('values:', s.values)   # NumPy array
print('index: ', s.index)

values: [2.  3.1 4.5]
index:  Index(['mon', 'tue', 'wed'], dtype='str')

### 1.3 Indexing a Series

Pandas offers two indexers:

| Indexer | Based on | Slice stop |
|---------|----------|------------|
| `.loc`  | **explicit** labels | **included** |
| `.iloc` | **implicit** position (0-based) | **excluded** |

In [10]:
s = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])

print(s.loc['a'])    # explicit index
print(s.iloc[0])     # implicit index (position)

# You can also assign values
s.loc['b'] = 10
print(s)

2.0
2.0
a     2.0
b    10.0
c     4.5
dtype: float64

In [13]:
# Slicing — note the different stop-inclusion rules!
s = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])

print(s.loc['a':'c'])   # stop label 'c' IS included
print()
print(s.iloc[1:3])      # stop position 3 is NOT included

a    2.0
b    3.1
c    4.5
dtype: float64

b    3.1
c    4.5
dtype: float64

In [14]:
# Boolean masking — select elements that satisfy a condition
s = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
print(s[(s > 2) & (s < 10)])

b    3.1
c    4.5
dtype: float64

In [16]:
# Fancy indexing — pass a list of labels or positions
s = pd.Series([2.0, 3.1, 4.5], index=['a', 'b', 'c'])
print(s.loc[['a', 'c']])
print()
print(s.iloc[[0, 2]])

a    2.0
c    4.5
dtype: float64

a    2.0
c    4.5
dtype: float64

---
## 2. Pandas DataFrame

A **DataFrame** is a 2-dimensional table where each column is a Series sharing the same index.

```
         Price   Quantity   Liters
Water      1.0          5      1.5
Beer       1.4         10      0.3
Wine       5.0          8      1.0
```

### 2.1 Creating a DataFrame

In [17]:
# From a dictionary of Series
price    = pd.Series([1.0, 1.4, 5.0], index=['a', 'b', 'c'])
quantity = pd.Series([5,   10,  8  ], index=['a', 'b', 'c'])
liters   = pd.Series([1.5, 0.3, 1.0], index=['a', 'b', 'c'])

df = pd.DataFrame({'Price': price, 'Quantity': quantity, 'Liters': liters})
print(df)

   Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [18]:
# From a dictionary of lists — index is automatic
dct = {'c1': [0, 1, 2], 'c2': [0, 2, 4]}
df2 = pd.DataFrame(dct)
print(df2)

   c1  c2
0   0   0
1   1   2
2   2   4

In [19]:
# From a list of dictionaries — each dict is one row
dict_list = [{'c1': i, 'c2': 2*i} for i in range(3)]
df3 = pd.DataFrame(dict_list)
print(df3)

   c1  c2
0   0   0
1   1   2
2   2   4

In [20]:
# From a 2D NumPy array
arr = np.arange(6).reshape((3, 2))
df4 = pd.DataFrame(arr, columns=['c1', 'c2'], index=['a', 'b', 'c'])
print(df4)

   c1  c2
a   0   1
b   2   3
c   4   5

### 2.2 Inspecting a DataFrame

In [21]:
df = pd.DataFrame({'Price':    [1.0, 1.4, 5.0],
                   'Quantity': [5,   10,  8  ],
                   'Liters':   [1.5, 0.3, 1.0]},
                  index=['a', 'b', 'c'])

print('Columns:', df.columns.tolist())
print('Index:  ', df.index.tolist())
print('Values (NumPy array):\n', df.values)

Columns: ['Price', 'Quantity', 'Liters']
Index:   ['a', 'b', 'c']
Values (NumPy array):
 [[ 1.   5.   1.5]
 [ 1.4 10.   0.3]
 [ 5.   8.   1. ]]

### 2.3 Accessing a DataFrame

The same `.loc` / `.iloc` indexers work for DataFrames.  
The syntax is `df.loc[row_selector, column_selector]`.

In [22]:
# Access a single column — returns a Series
print(df['Quantity'])

a     5
b    10
c     8
Name: Quantity, dtype: int64

In [23]:
# Access a single row by explicit / implicit index
print(df.loc['a'])    # explicit
print()
print(df.iloc[0])     # implicit

Price       1.0
Quantity    5.0
Liters      1.5
Name: a, dtype: float64

Price       1.0
Quantity    5.0
Liters      1.5
Name: a, dtype: float64

In [25]:
# Slicing — select a range of rows AND columns
print(df.loc['b':'c', 'Quantity':'Liters'])

   Quantity  Liters
b        10     0.3
c         8     1.0

In [26]:
# Boolean masking — select rows based on a condition
mask = (df['Quantity'] < 10) & (df['Liters'] > 1)
print(df.loc[mask, 'Quantity':])   # masking + slicing

   Quantity  Liters
a         5     1.5

In [27]:
# Fancy indexing — pick arbitrary rows and columns by name
print(df.loc[['a', 'c'], ['Price', 'Liters']])

   Price  Liters
a    1.0     1.5
c    5.0     1.0

### 2.4 Modifying a DataFrame

In [28]:
df_mod = df.copy()

# Assign a value to a selection
df_mod.loc[['a', 'c'], ['Price', 'Liters']] = 0
print(df_mod)

   Price  Quantity  Liters
a    0.0         5     0.0
b    1.4        10     0.3
c    0.0         8     0.0

In [29]:
# Add a new column (from a list or a Series)
df_mod = df.copy()
df_mod['Available'] = [True, False, True]
print(df_mod)

   Price  Quantity  Liters  Available
a    1.0         5     1.5       True
b    1.4        10     0.3      False
c    5.0         8     1.0       True

In [30]:
# Drop columns - returns a copy by default
df_dropped = df_mod.drop(columns=['Quantity', 'Liters'])
print(df_dropped)

   Price  Available
a    1.0       True
b    1.4      False
c    5.0       True

In [31]:
# Rename columns using a mapping dictionary
df_renamed = df_mod.rename(columns={'Quantity': 'nItems', 'Liters': '[L]'})
print(df_renamed)

   Price  nItems  [L]  Available
a    1.0       5  1.5       True
b    1.4      10  0.3      False
c    5.0       8  1.0       True

---
## 3. I/O — Reading and Writing Data

Pandas can read and write many file formats. The most common is **CSV**.

### 3.1 Reading a CSV file

In [ ]:
# Create a small sample CSV to work with
csv_content = """c1,c2,c3
0,1,2

3,4,5
6,7,8
"""
with open('sample.csv', 'w') as f:
    f.write(csv_content)

   c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

In [33]:
df_csv = pd.read_csv('sample.csv', sep=',')
print(df_csv)

   c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

In [34]:
# Handling missing values — specify which strings mean "missing"
csv_missing = """c1,c2,c3
0,no info,
3,4,5
6,x,NaN
"""
with open('sample_missing.csv', 'w') as f:
    f.write(csv_missing)

In [35]:

df_na = pd.read_csv('sample_missing.csv', na_values=['no info', 'x'])
print(df_na)
print('\nData types:\n', df_na.dtypes)

   c1   c2   c3
0   0  NaN  NaN
1   3  4.0  5.0
2   6  NaN  NaN

Data types:
 c1      int64
c2    float64
c3    float64
dtype: object

### 3.2 Writing a CSV file

In [36]:
# Save to CSV — use index=False to avoid writing the row index
df_csv.to_csv('output.csv', sep=',', index=False)

# Verify by reading it back
print(pd.read_csv('output.csv'))

   c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

> **Tip:** Pandas also supports Excel (`read_excel`), JSON (`read_json`), HTML, HDF5 and many more.
> See the full list at https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

---
## 4. Computation with Pandas

### 4.1 Unary operations

NumPy universal functions (`ufuncs`) work directly on Series and DataFrames, element-wise.

In [38]:
my_series = pd.Series([1.0, 2.0, 3.0, 4.0])

print(my_series / 4 + 1)
print()
print(np.exp(my_series))

0    1.25
1    1.50
2    1.75
3    2.00
dtype: float64

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

### 4.2 Operations between Series

Arithmetic operations align on the **index** automatically.  
Elements whose index does not match in both Series will produce **NaN**.

In [39]:
s1 = pd.Series([1, 3, 10], index=['a', 'b', 'c'])
s2 = pd.Series([1, 3, 30], index=['a', 'b', 'd'])

print(s1 + s2)  # 'c' and 'd' have no match → NaN

a    2.0
b    6.0
c    NaN
d    NaN
dtype: float64

### 4.3 Operations between DataFrames

The same alignment logic applies to both **index** and **columns**.

In [40]:
df1 = pd.DataFrame({'Total': [3, 1, 10], 'Quantity': [4, 2, 20]},
                   index=['b', 'a', 'c'])
df2 = pd.DataFrame({'Total': [1, 3, 30], 'Quantity': [2, 4, 40]},
                   index=['a', 'b', 'd'])

print(df1 + df2)  # row 'c' and 'd' have no match → NaN

   Total  Quantity
a    2.0       4.0
b    6.0       8.0
c    NaN       NaN
d    NaN       NaN

### 4.4 Aggregation functions

For DataFrames, aggregation functions are applied **column-wise** and return a Series.

In [41]:
data = pd.DataFrame({'Total':    [1, 3, 5],
                     'Quantity': [2, 4, 6]},
                    index=['a', 'b', 'c'])

print('mean:\n', data.mean())
print('\nstd:\n', data.std())
print('\nmin:\n', data.min())

mean:
 Total       3.0
Quantity    4.0
dtype: float64

std:
 Total       2.0
Quantity    2.0
dtype: float64

min:
 Total       1
Quantity    2
dtype: int64

In [43]:
# Practical example: z-score normalization
mean_s = data.mean()
std_s  = data.std()
data_norm = (data - mean_s) / std_s
print(data_norm)

   Total  Quantity
a   -1.0      -1.0
b    0.0       0.0
c    1.0       1.0

---
## 5. Missing Values

Pandas represents missing data using:
- `None` — Python's null object (any dtype)
- `np.nan` — a floating-point sentinel (preferred for numerical data, better performance)

Pandas automatically converts between them when needed.

In [53]:
s = pd.Series([4, None, 5, np.nan])
print(s)          # Both None and np.nan become NaN
print('dtype:', s.dtype)

0    4.0
1    NaN
2    5.0
3    NaN
dtype: float64
dtype: float64

In [45]:
# isnull() — boolean mask of missing values
print(s.isnull())
print()
# notnull() — the inverse
print(s.notnull())

0    False
1     True
2    False
3     True
dtype: bool

0     True
1    False
2     True
3    False
dtype: bool

In [46]:
# dropna() — remove missing values
print(s.dropna())

0    4.0
2    5.0
dtype: float64

In [52]:
# dropna() on a DataFrame: by default removes any row with at least one NaN
df_miss = pd.DataFrame({'Total':    [1, 3,   5],
                        'Quantity': [2, None, 6]},
                       index=['a', 'b', 'c'])
print('Original:\n', df_miss)
print('\nAfter dropna():\n', df_miss.dropna())

Original:
    Total  Quantity
a      1       2.0
b      3       NaN
c      5       6.0

After dropna():
    Total  Quantity
a      1       2.0
c      5       6.0

In [48]:
# fillna() — replace NaN with a fixed value
print(s.fillna(0))

0    4.0
1    0.0
2    5.0
3    0.0
dtype: float64

In [56]:
# fillna() with forward fill (ffill) — propagate the last valid value
print(s.ffill())

0    4.0
1    4.0
2    5.0
3    5.0
dtype: float64

---
## 6. Grouping Data

Pandas `groupby` is the equivalent of SQL `GROUP BY`.  
The typical workflow is: **split** → **apply** → **combine**.

1. Split the DataFrame into groups based on a key column
2. Apply a function to each group (aggregation, filter, transform)
3. Combine the results

In [57]:
df_g = pd.DataFrame({'k':  ['a', 'b', 'a', 'b'],
                     'c1': [2,   10,  3,   15],
                     'c2': [4,   20,  5,   30]})
print(df_g)

grouped = df_g.groupby('k')   # creates a DataFrameGroupBy object

   k  c1  c2
0  a   2   4
1  b  10  20
2  a   3   5
3  b  15  30

In [60]:
# Iterate over groups
for key, group_df in grouped:
    print(f'--- Group: {key} ---')
    print(group_df)

--- Group: a ---
   k  c1  c2
0  a   2   4
2  a   3   5
--- Group: b ---
   k  c1  c2
1  b  10  20
3  b  15  30

In [61]:
# Aggregate all columns — result index is the group key
print(grouped.mean())

     c1    c2
k
a   2.5   4.5
b  12.5  25.0

In [62]:
# Aggregate a single column — returns a Series
print(grouped['c1'].mean())

k
a     2.5
b    12.5
Name: c1, dtype: float64

In [63]:
# Filter groups: keep only groups where mean of c1 > 5
result = grouped.filter(lambda x: x['c1'].mean() > 5)
print(result)

   k  c1  c2
1  b  10  20
3  b  15  30

---
## 7. Combining DataFrames

### 7.1 Concatenation

`pd.concat()` stacks Series or DataFrames along an axis.  
Indices are preserved (duplicates are allowed).

In [64]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[1, 2])

# Default: keep original indices (may create duplicates)
print(pd.concat((s1, s2)))

1    a
2    b
1    c
2    d
dtype: str

In [65]:
# Use ignore_index=True to get a fresh numeric index
print(pd.concat((s1, s2), ignore_index=True))

0    a
1    b
2    c
3    d
dtype: str

In [66]:
# Concatenating DataFrames — vertical by default
df1 = pd.DataFrame({'Total': [1, 3], 'Quantity': [2, 4]}, index=['a', 'b'])
df2 = pd.DataFrame({'Total': [5, 7], 'Quantity': [6, 8]}, index=['c', 'd'])

print(pd.concat((df1, df2)))

   Total  Quantity
a      1         2
b      3         4
c      5         6
d      7         8

In [67]:
# If columns differ, missing values are filled with NaN
df3 = pd.DataFrame({'Total': [5, 7], 'Quantity': [6, 8], 'Liters': [1.0, 2.0]},
                   index=['c', 'd'])
print(pd.concat((df1, df3)))

   Total  Quantity  Liters
a      1         2     NaN
b      3         4     NaN
c      5         6     1.0
d      7         8     2.0

### 7.2 Merging (Relational Join)

`pd.merge()` joins two DataFrames like a SQL JOIN.  
By default it merges on columns with the **same name** in both DataFrames.

In [70]:
# One-to-one merge
left  = pd.DataFrame({'k1': [0, 1], 'c2': ['a', 'b']}, index=['i1', 'i2'])
right = pd.DataFrame({'k1': [1, 0], 'c3': ['b1', 'a1']}, index=['i1', 'i2'])

print(pd.merge(left, right))   # merge on 'k1'

   k1 c2  c3
0   0  a  a1
1   1  b  b1

In [71]:
# Many-to-one merge
left_m = pd.DataFrame({'k1': [0, 1, 0, 1], 'c2': ['a', 'b', 'c', 'd']})
right_m = pd.DataFrame({'k1': [1, 0], 'c3': ['b1', 'a1']})

print(pd.merge(left_m, right_m))

   k1 c2  c3
0   0  a  a1
1   1  b  b1
2   0  c  a1
3   1  d  b1

---
## 8. Pivoting

`pivot_table()` is useful to summarise a dataset by two categorical variables — very similar to Excel pivot tables.

In [72]:
# Sensor failure dataset
df_piv = pd.DataFrame({
    'type':  ['a','b','b','a','b','a','b','a'],
    'class': [3,  2,  3,  3,  2,  1,  1,  2],
    'fail':  [1,  1,  1,  0,  1,  0,  0,  0]
})
print(df_piv)

  type  class  fail
0    a      3     1
1    b      2     1
2    b      3     1
3    a      3     0
4    b      2     1
5    a      1     0
6    b      1     0
7    a      2     0

In [73]:
# Total number of failures per (type, class)
df_piv.pivot_table('fail', index='type', columns='class', aggfunc='sum')

class  1  2  3
type
a      0  0  1
b      0  2  1

In [74]:
# Failure rate per (type, class)
df_piv.pivot_table('fail', index='type', columns='class', aggfunc='mean')

class    1    2    3
type
a      0.0  0.0  0.5
b      0.0  1.0  1.0

---
## 9. Multi-Index

A **Multi-Index** adds a hierarchy of labels to rows (or columns), letting you index data by multiple levels at once.  
A classic use case: data indexed by both *city* and *year*.

### 9.1 Multi-indexed Series

In [77]:
ix = [['Rome', 'Rome', 'Turin', 'Turin'],
      ['2018', '2019', '2018', '2019']]

s_mi = pd.Series([10, 13, 7, 9], index=ix)
s_mi = s_mi.sort_index()          # always sort a multi-index before slicing!
s_mi.index.names = ['city', 'year']
print(s_mi)

city   year
Rome   2018    10
       2019    13
Turin  2018     7
       2019     9
dtype: int64

In [81]:
# Access by outer level
print(s_mi.loc['Turin'])

year
2018    7
2019    9
dtype: int64

In [83]:
# Access a specific inner level across all outer levels
print(s_mi.loc[:, '2018'])   # all cities, only year 2018

city
Rome     10
Turin     7
dtype: int64

In [84]:
# Boolean masking still works
print(s_mi[s_mi > 10])

city  year
Rome  2019    13
dtype: int64

### 9.2 Multi-indexed DataFrame

In [92]:
ix   = [['Rome', 'Rome', 'Turin', 'Turin'], ['2018', '2019', '2018', '2019']]
cols = [['c1','c1','c2','c2'], ['a','b','a','b']]
data = np.arange(16).reshape((4, 4))

df_mi = pd.DataFrame(data, index=ix, columns=cols)
print(df_mi)

            c1      c2
             a   b   a   b
Rome  2018   0   1   2   3
      2019   4   5   6   7
Turin 2018   8   9  10  11
      2019  12  13  14  15

In [93]:
# Access outer column level
print(df_mi['c1'])

             a   b
Rome  2018   0   1
      2019   4   5
Turin 2018   8   9
      2019  12  13

In [94]:
# Access both column levels
print(df_mi['c1', 'a'])

Rome   2018     0
       2019     4
Turin  2018     8
       2019    12
Name: (c1, a), dtype: int64

In [95]:
# pd.IndexSlice for precise multi-index slicing
ix_sl = pd.IndexSlice
print(df_mi.loc[ix_sl['Rome', '2018'], ix_sl['c1':'c2', 'a']])

c1  a    0
c2  a    2
Name: (Rome, 2018), dtype: int64

### 9.3 `reset_index` and `set_index`

In [96]:
# reset_index — turns the multi-index into regular columns
df_mi.index.names = ['city', 'year']
df_reset = df_mi.reset_index()
print(df_reset)

    city  year  c1      c2
                 a   b   a   b
0   Rome  2018   0   1   2   3
1   Rome  2019   4   5   6   7
2  Turin  2018   8   9  10  11
3  Turin  2019  12  13  14  15

In [97]:
# set_index — inverse of reset_index
df_back = df_reset.set_index(['city', 'year'])
print(df_back)

            c1      c2
             a   b   a   b
city  year
Rome  2018   0   1   2   3
      2019   4   5   6   7
Turin 2018   8   9  10  11
      2019  12  13  14  15

### 9.4 `unstack` and `stack`

In [101]:
# unstack — move an index level to columns (multi-index Series → DataFrame)
print(s_mi.unstack())

year   2018  2019
city
Rome     10    13
Turin     7     9

In [102]:
# stack — inverse: move a column level to the index (DataFrame → multi-index Series)
print(s_mi.unstack().stack())

city   year
Rome   2018    10
       2019    13
Turin  2018     7
       2019     9
dtype: int64

---
## 10. Quick Reference Cheat Sheet

| Task | Code |
|------|------|
| Create Series from list | `pd.Series([1, 2, 3])` |
| Create DataFrame from dict | `pd.DataFrame({'a': [1,2], 'b': [3,4]})` |
| Read CSV | `pd.read_csv('file.csv')` |
| Write CSV | `df.to_csv('file.csv', index=False)` |
| Select column | `df['col']` |
| Select row (label) | `df.loc['row']` |
| Select row (position) | `df.iloc[0]` |
| Boolean mask | `df[df['col'] > 5]` |
| Add column | `df['new'] = values` |
| Drop column | `df.drop(columns=['col'])` |
| Fill NaN | `df.fillna(0)` |
| Drop NaN rows | `df.dropna()` |
| Group by | `df.groupby('col').mean()` |
| Pivot table | `df.pivot_table(val, index=rows, columns=cols, aggfunc='sum')` |
| Concatenate | `pd.concat([df1, df2])` |
| Merge (join) | `pd.merge(df1, df2)` |